version: '3.8'

services:
  fee-calculator:
    image: php:8.3-cli
    volumes:
      - .:/app
    working_dir: /app
    command: php app.php input.txt
    env_file:
      - ./local.env

  phpunit:
    image: php:8.3-cli
    volumes:
      - .:/app
    working_dir: /app
    command: php vendor/bin/codecept run Unit
